# Generated by Django 4.1.3 on 2022-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Cargo', models.CharField(max_length=8)),
                ('Dias_Trabajados', models.BigIntegerField()),
                ('Total_Salario', models.BigIntegerField()),
                ('Mes_Pagado', models.BigIntegerField()),
            ],
        ),
    ]
